tag-template: forensics-api-$NEXT_PATCH_VERSION
name-template: Forensics API $NEXT_PATCH_VERSION 🎁

template: |
  $CHANGES

categories:
  - title: 🚨 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 📝 Documentation updates
    label: documentation
  - title: 📦 Dependency updates
    label: dependencies
  - title: 🔧 Internal changes
    label: internal
  - title: 🚦 Tests
    labels:
      - test
      - tests

replacers:
  - search: '/\[*JENKINS-(\d+)\]*\s*-*\s*/g'
    replace: '[JENKINS-$1](https://issues.jenkins-ci.org/browse/JENKINS-$1) - '
